android_binary(
    name = "AndroidNougatEasterEgg",
    srcs = glob(["src/**/*.java"]),
    custom_package = "com.covertbagel.neko",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = [
        "@com_android_support//:recyclerview-v7-25.3.1",
        "@com_android_support//:support-annotations-25.3.1",
        "@com_android_support//:support-compat-25.3.1",
        "@com_android_support//:support-core-ui-25.3.1",
    ],
)
