android_binary(
    name = "AndroidNougatEasterEgg",
    srcs = glob(["src/**/*.java"]),
    custom_package = "com.covertbagel.neko",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = [
        "@androidsdk//com.android.support:recyclerview-v7-25.3.1",
        "@androidsdk//com.android.support:support-annotations-25.3.1",
        "@androidsdk//com.android.support:support-compat-25.3.1",
        "@androidsdk//com.android.support:support-core-ui-25.3.1",
    ],
)

